version: "3"

services:
  web:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./web.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      web:

networks:
  web:
    driver: bridge
